name: Tests

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
  push:
    branches: [ "enh/update-github-actions-for-building-rasterio" ]

defaults:
  run:
    shell: bash

jobs:
  Pytest:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.14"]
    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python-version }}
      MPLBACKEND: Agg
    steps:
      - uses: actions/checkout@main
      - name: Set up Conda and Environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          miniforge-variant: Miniforge3
          channels: conda-forge
          run-post: false
          activate-environment: test-env

      - name: Install GDAL and Rasterio via Conda
        run: |
          mamba install -y gdal gdal-config

      - name: Install rocketpy
        run: pip install .

      - name: Test importing rocketpy
        run: python -c "import sys, rocketpy; print(f'{rocketpy.__name__} running on Python {sys.version}')"

      - name: Install test dependencies
        run: |
          pip install -r requirements-tests.txt
          pip install .[all]

      - name: Run Unit Tests
        run: pytest tests/unit --cov=rocketpy

      - name: Run Documentation Tests
        run: |
          pip install numpy --upgrade
          pytest rocketpy --doctest-modules --cov=rocketpy --cov-append

      - name: Run Integration Tests
        run: pytest tests/integration --cov=rocketpy --cov-append

      - name: Run Acceptance Tests
        run: pytest tests/acceptance --cov=rocketpy --cov-append --cov-report=xml

      - name: Upload coverage to artifacts
        uses: actions/upload-artifact@main
        with:
          name: coverage
          path: coverage.xml
          overwrite: true
          if-no-files-found: error

  CodecovUpload:
    needs: Pytest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Download latest coverage report
        uses: actions/download-artifact@main
      - name: Upload to Codecov
        uses: codecov/codecov-action@main
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: |
            coverage.xml
